# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 486596f6d17274e721ce42dfbe8fd51d3854c9951d02662cfc3ef38898f5b790d5fb097e5bedb436ab505f7f59a3229de6f97dd8c19358f2b6e0c267c11b536e

test:
  secret_key_base: c9f293c4a7288c5c0688a3e5f58dbc2ef16c86c8f4ea1be2343bab30c1bd09f1427a1f093ba0fb1fe7385226cc38b839c5b957ecdb58ce960ac49fcc184aa6cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
